# Generated by Django 3.2.16 on 2023-06-23 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitals',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='vitals',
            name='timestramp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
